@echo off
echo ========================================
echo  Time Attendance System
echo  Network Access Setup
echo ========================================
echo.

REM Get server IP address
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set IP=%%a
    goto :found
)

:found
REM Trim spaces
for /f "tokens=* delims= " %%a in ("%IP%") do set SERVER_IP=%%a

echo Detected Server IP: %SERVER_IP%
echo.

echo [1/5] Creating frontend environment configuration...
echo.

REM Create frontend .env file
(
echo # Frontend Environment Configuration
echo # Generated by setup_network_access.bat
echo.
echo # Backend API URL - Network Access
echo REACT_APP_API_URL=http://%SERVER_IP%:5000
echo.
echo # Alternative: Use this for localhost testing only
echo # REACT_APP_API_URL=http://localhost:5000
echo.
echo # Port configuration
echo PORT=3000
echo.
echo # Browser auto-open
echo BROWSER=none
) > frontend\.env

echo ✓ Frontend .env file created
echo.

echo [2/5] Verifying backend configuration...
echo.

REM Check if backend .env has correct CORS settings
findstr /C:"%SERVER_IP%" backend\.env >nul
if %errorlevel%==0 (
    echo ✓ Backend already configured for network access
) else (
    echo ! Adding network IP to backend CORS settings...
    echo. >> backend\.env
    echo # Network access configuration >> backend\.env
    echo ALLOWED_ORIGINS=http://localhost:3000,http://%SERVER_IP%:3000 >> backend\.env
    echo ✓ Backend configuration updated
)
echo.

echo [3/5] Checking Windows Firewall...
echo.

REM Check if firewall rules exist
netsh advfirewall firewall show rule name="Time Attendance System" >nul 2>&1
if %errorlevel%==0 (
    echo ✓ Firewall rules already exist
) else (
    echo ! Firewall rules not found
    echo.
    echo   To allow network access, run this as Administrator:
    echo   netsh advfirewall firewall add rule name="Time Attendance System" dir=in action=allow protocol=TCP localport=3000,5000
    echo.
    echo   OR manually configure Windows Firewall:
    echo   - Open Windows Defender Firewall with Advanced Security
    echo   - Create Inbound Rule for TCP ports 3000 and 5000
    echo.
)

echo [4/5] Creating system information file...
echo.

REM Create access information file
(
echo ========================================
echo  TIME ATTENDANCE SYSTEM - ACCESS INFO
echo ========================================
echo.
echo Server IP Address: %SERVER_IP%
echo Generated on: %DATE% %TIME%
echo.
echo ACCESS URLS:
echo ----------------------------------------
echo.
echo On This Server PC:
echo   http://localhost:3000
echo.
echo From Other Computers on Network:
echo   http://%SERVER_IP%:3000
echo.
echo Backend API:
echo   http://%SERVER_IP%:5000
echo.
echo ========================================
echo INSTRUCTIONS:
echo ========================================
echo.
echo 1. Start the system using: start_system.bat
echo.
echo 2. Share this URL with users:
echo    http://%SERVER_IP%:3000
echo.
echo 3. Users should connect to the same network
echo.
echo 4. Keep this server PC running
echo.
echo 5. Default login credentials:
echo    Email: susaraperera33@gmail.com
echo    Password: susara_perera
echo.
echo ========================================
) > NETWORK_ACCESS_INFO.txt

echo ✓ Access information saved to NETWORK_ACCESS_INFO.txt
echo.

echo [5/5] Setup Summary
echo ========================================
echo.
echo ✓ Frontend configured for network access
echo ✓ Backend CORS settings verified
echo ✓ Access information generated
echo.
echo YOUR ACCESS URLs:
echo ----------------------------------------
echo.
echo 🖥️  On this PC:
echo    http://localhost:3000
echo.
echo 🌐 On network devices:
echo    http://%SERVER_IP%:3000
echo.
echo ========================================
echo.
echo NEXT STEPS:
echo 1. Configure Windows Firewall (if not done)
echo 2. Run: start_system.bat
echo 3. Access from any browser: http://%SERVER_IP%:3000
echo.
echo ========================================
echo.

pause
