import React, { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  en: {
    systemSettings: 'System Settings',
    dashboard: 'Dashboard',
    systemTitle: 'Time Attendance System',
    welcome: 'Welcome',
    welcomeAdmin: 'Welcome Admin',
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    refresh: 'Refresh',
    logout: 'Logout',
    admin: 'Admin',
    saveChanges: 'Save Changes',
    quickActions: 'Quick Actions',
    addUser: 'Add User',
    reportGeneration: 'Report Generation',
    reportGenerationTitle: 'Report Generation Center',
    reportGenerationSubtitle: 'Generate comprehensive attendance and meal reports with advanced filtering options',
    reportTypeLabel: 'Report Type',
    reportScopeLabel: 'Report Scope',
    attendanceReport: 'Attendance Report',
    mealReport: 'Meal Report',
    auditReport: 'Audit Report',
    individualReport: 'Individual Report',
    groupReport: 'Group Report',
    startDateLabel: 'Start Date',
    endDateLabel: 'End Date',
    enterEmployeeId: 'Enter employee ID',
    generateReport: 'Generate Report',
    generating: 'Generating...',
    noDataFoundTitle: 'No Data Found',
    noDataFoundText: 'No records found for the selected criteria. Try adjusting your filters.',
    readyToGenerateTitle: 'Ready to Generate Reports',
    readyToGenerateText: 'Configure your report parameters above and click "Generate Report" to start.',
    mealManagementTitle: 'Meal Management',
    bookNewMeal: 'Book New Meal',
    divisionLabel: 'Division',
    sectionLabel: 'Section',
    mealDateLabel: 'Meal Date',
    mealTypeLabel: 'Meal Type',
    selectMealType: 'Select Meal Type',
    mealTypeBreakfast: '🌅 Breakfast',
    mealTypeLunch: '☀️ Lunch',
    mealTypeDinner: '🌙 Dinner',
    mealTypeSnack: '🍪 Snack',
    expectedQuantityLabel: 'Expected Quantity',
    specialRequirementsLabel: 'Special Requirements',
    specialRequirementsPlaceholder: 'Any dietary restrictions, allergies, or special instructions...',
    bookMeal: 'Book Meal',
    bookingInProgress: 'Booking...',
    todaysBookingsLabel: "Today's Bookings",
    bookingInfoTitle: 'Booking Information',
    bookingInfo_line1: 'Bookings must be made in advance',
    bookingInfo_line2: 'Booking deadline: 09:00 AM daily',
    bookingInfo_line3: 'Standard meals available in cafeteria',
    bookingInfo_line4: 'Special dietary requirements noted',
    bookingInfo_line5: 'Reports available in Report Generation',
    errorFetchingDivisions: 'Error fetching divisions. Please try again.',
    errorFetchingSections: 'Error fetching sections. Please try again.',
    mealBookingCreated: 'Meal booking created successfully!',
    mealBookingCreateError: 'Error creating meal booking',
    mealBookingNetworkError: 'Network error occurred while creating meal booking',
    mealManagement: 'Meal Management',
    divisionManagementTitle: 'Division Management',
    noPermissionViewDivisions: 'You do not have permission to view divisions. Contact a Super Admin for access.',
    divisionSearchLabel: 'Search:',
    divisionSearchPlaceholder: 'Search by Division Code or Name',
    divisionCodeHeader: 'Division Code',
    divisionNameHeader: 'Division Name',
    divisionStatusHeader: 'Status',
    divisionCreatedDateHeader: 'Created Date',
    actionsHeader: 'Actions',
    viewDivisionDetails: 'View Division Details',
    viewLabel: 'View',
    activeLabel: 'Active',
    inactiveLabel: 'Inactive',
    naLabel: 'N/A',
    noDivisionsFoundMsg: 'No divisions found. Click "Add Division" to create the first division.',
    addDivision: 'Add Division',
    divisionDetailsTitle: 'Division Details',
    confirmDeleteDivision: 'Are you sure you want to delete "{name}" division? This action cannot be undone.',
    divisionDeletedSuccess: 'Division deleted successfully!',
    divisionCreatedSuccess: 'Division created successfully!',
    divisionUpdatedSuccess: 'Division updated successfully!',
    divisionManagement: 'Division Management',
    sectionManagement: 'Section Management',
    rolesPermissions: 'Roles & Permissions',
    employeeManagement: 'Employee Management',
    attendanceSystem: 'ATTENDANCE SYSTEM',
    poweredBy: '@Powered By IS Division',
    slpaTitle: 'SLPA TIME ATTENDANCE SYSTEM',
    createdBy: 'Created By: IS Division',
    closeSidebar: 'Close Sidebar',
    toggleSidebar: 'Toggle Sidebar',
    profile: 'Profile',
    settings: 'Settings',
    general: 'General',
    appearance: 'Appearance',
    security: 'Security',
    notifications: 'Notifications',
    dataExport: 'Data Export',
    language: 'Language',
    theme: 'Theme',
    workingHours: 'Working Hours',
    startTime: 'Start Time',
    endTime: 'End Time',
    enableNotificationSound: 'Enable Notification Sound',
    notificationEmails: 'Notification Emails',
    addMail: 'Add Mail',
    noEmails: 'No notification emails added yet.',
    // Password / security UI
    changePasswordTitle: 'Change Password',
    enterCurrentPasswordPlaceholder: 'Enter current password',
    verifyingPassword: 'Verifying...',
    verifyPasswordFailed: 'Current password is incorrect',
    enterNewPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    changePasswordButton: 'Change Password',
    forgotPasswordText: 'Forgot password?',
    forgotPasswordInstructions: 'Enter your account email to receive a reset link.',
    resetEmailSentMsg: 'If the email exists, a password reset link has been sent.',
    passwordMismatch: 'Passwords do not match',
    passwordChangedSuccess: 'Password changed successfully!',
    passwordChangeError: 'Error changing password. Please try again.',
    systemName: 'System Name',
    timezone: 'Timezone',
    totalEmployees: 'Total Employees',
    allSubsections: 'All sub-sections',
    presentToday: 'Present Today',
    activeAttendance: 'Active attendance',
    attendanceRateLabel: 'attendance rate',
    activeDivisions: 'Active Divisions',
    allDivisions: 'All divisions',
    totalSections: 'Total Sections',
    totalSubSections: 'Total Sub-Sections',
    todaysAttendance: "Today's Attendance",
    presentLabel: 'Present',
    absentLabel: 'Absent',
    monthlyAttendance: 'Monthly Attendance',
    export: 'Export',
    quickInsights: 'Quick Insights',
    highAttendance: 'High Attendance',
    lateArrivals: 'Late Arrivals',
    earlyDepartures: 'Early Departures',
    recentActivity: 'Recent Activity',
    noRecentActivities: 'No recent activities found.',
    showAll: 'Show All',
    close: 'Close',
    divisionManagementTitle: 'Division Management',
    noPermissionViewDivisions: 'You do not have permission to view divisions. Contact a Super Admin for access.',
    divisionSearchLabel: 'Search:',
    divisionSearchPlaceholder: 'Search by Division Code or Name',
    divisionCodeHeader: 'Division Code',
    divisionNameHeader: 'Division Name',
    divisionStatusHeader: 'Status',
    divisionCreatedDateHeader: 'Created Date',
    actionsHeader: 'Actions',
    viewDivisionDetails: 'View Division Details',
    viewLabel: 'View',
    activeLabel: 'Active',
    inactiveLabel: 'Inactive',
    naLabel: 'N/A',
    noDivisionsFoundMsg: 'No divisions found. Click "Add Division" to create the first division.',
    addDivision: 'Add Division',
    divisionDetailsTitle: 'Division Details',
    confirmDeleteDivision: 'Are you sure you want to delete "{name}" division? This action cannot be undone.',
    divisionDeletedSuccess: 'Division deleted successfully!',
    divisionCreatedSuccess: 'Division created successfully!',
    divisionUpdatedSuccess: 'Division updated successfully!',
    userManagement: 'User Management',
    noPermissionViewUsers: 'You do not have permission to view users. Contact a Super Admin for access.',
    editUser: 'Edit User',
    addNewUser: 'Add New User',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailLabel: 'Email',
    employeeIdLabel: 'Employee ID',
    divisionLabel: 'Division',
    selectDivision: 'Select Division',
    roleLabel: 'Role',
    sectionLabel: 'Section',
    selectSection: 'Select Section',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    cancel: 'Cancel',
    updateUser: 'Update User',
    noPermissionAddUser: 'You do not have permission to add users',
    noUsersFound: 'No users found. Click "Add User" to create the first user.' ,
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    userDeletedSuccess: 'User deleted successfully!',
    userCreateSuccess: 'User created successfully!',
    userUpdateSuccess: 'User updated successfully!',
    passwordsDoNotMatch: 'Passwords do not match!',
    pleaseFillRequired: 'Please fill in all required fields!',
    passwordRequired: 'Password is required for new users!',
    failedToSaveUser: 'Failed to save user',
    loading: 'Loading...',
    nameLabel: 'Name',
    statusLabel: 'Status',
    actionsLabel: 'Actions',
    employeeManagement: 'Employee Management',
    employeeHeaderSubtitle: 'View all employee records from HRIS API with division and section filtering',
    activeFiltersLabel: 'Active Filters:',
    allDivisionsLabel: 'All Divisions',
    allSectionsLabel: 'All Sections',
    allSubSectionsLabel: 'All Sub-Sections',
    selectDivisionFirst: 'Select division first',
    selectSectionFirst: 'Select section first',
    noSections: 'No sections',
    noSubsections: 'No sub-sections',
    searchLabel: 'Search',
    searchPlaceholder: 'Search by ID, Name, Designation, NIC...',
    clearSearchTitle: 'Clear search',
    fetchingHris: 'Fetching employee data from HRIS API...',
    noEmployeesFoundMsg: 'No employees found',
    fullNameLabel: 'Full Name',
    designationLabel: 'Designation',
    genderLabel: 'Gender',
    nicLabel: 'NIC',
    subSectionLabel: 'Sub-Section',
  },
  si: {
    systemSettings: 'පද්ධති සැකසුම්',
    quickActions: 'හාඩ් ක්‍රියා',
    addUser: 'පරිශීලක එක් කරන්න',
    reportGeneration: 'වාර්තා ජනනය',
    mealManagement: 'ආහාර කළමනාකරණය',
    divisionManagement: 'වකවානු කළමනාකරණය',
    sectionManagement: 'කලාප කළමනාකරණය',
    rolesPermissions: 'භූමිකා සහ අවසර',
    employeeManagement: 'සේවක කළමනාකරණය',
    attendanceSystem: 'ATTENDANCE SYSTEM',
    poweredBy: '@Powered By IS Division',
    slpaTitle: 'SLPA TIME ATTENDANCE SYSTEM',
    createdBy: 'Created By: IS Division',
    closeSidebar: 'යිතුරු තිරය වසා දැමීම',
    toggleSidebar: 'පසුරුව තිරය',
    profile: 'ප්රොෆයිල්',
    settings: 'සැකසුම්',
    dashboard: 'Dashboard',
    systemTitle: 'Time Attendance System',
    welcome: 'ආයුබෝවන්',
    welcomeAdmin: 'ආයුබෝවන් ප්‍රධානියා',
    greetingMorning: 'සුභ උදෑසනක්',
    greetingAfternoon: 'සුභ දවල්වලක්',
    greetingEvening: 'සුභ සවසක්',
    refresh: 'නවීකරණය',
    logout: 'පිටවීම',
    admin: 'පරිපාලක',
    saveChanges: 'වෙනස්කම් සුරකින්න',
    general: 'සාමාන්‍ය',
    appearance: 'පෙනුම',
    security: 'පූර්ව ආරක්ෂාව',
    notifications: 'ලකුණු',
    dataExport: 'දත්ත අපනයන',
    language: 'භාෂාව',
    theme: 'තේමාව',
    workingHours: 'වැඩ කරන වේලාව',
    startTime: 'ආරම්භක වේලාව',
    endTime: 'අවසන් වේලාව',
    enableNotificationSound: 'යහළුවාගැනුම් ශබ්ද සක්‍රිය කරන්න',
    notificationEmails: 'දැනුම්දීම් විද්‍යුත් ලිපින',
    addMail: 'ලිපිනය එකතු කරන්න',
    noEmails: 'තවම විද්‍යුත් ලිපින එක් කර නැත.',
    systemName: 'පද්ධති නම',
    timezone: 'වේලා කලාපය',
    userManagement: 'පරිශීලක කළමනාකරණය',
    noPermissionViewUsers: 'ඔබට පරිශීලකයන් නරඹා බලන්න අවසර නැත. ප්‍රවීණ පරිපාලකයෙකු සම්බන්ධ වන්න.',
    editUser: 'පරිශීලකයින් සංස්කරණය කරන්න',
    addNewUser: 'නව පරිශීලකයෙකු එකතු කරන්න',
    firstName: 'මුල් නම',
    lastName: 'හස්ත නම',
    emailLabel: 'ඊමේල්',
    employeeIdLabel: 'සේවක ID',
    divisionLabel: 'වර්ගය',
    selectDivision: 'වර්ගය තෝරන්න',
    roleLabel: 'භූමිකාව',
    sectionLabel: 'අංශය',
    selectSection: 'අංශය තෝරන්න',
    passwordLabel: 'මුරපදය',
    confirmPasswordLabel: 'මුරපදය තහවුරු කරන්න',
    cancel: 'වල්ගන්න',
    updateUser: 'පරිශීලක යාවත්කාලීන කරන්න',
    noPermissionAddUser: 'පරිශීලකයන් එක් කිරීමට ඔබට අවසර නොමැත',
    noUsersFound: 'පරිශීලකයන් නොමැත. ප්‍රථම පරිශීලකයා නිර්මාණය කිරීමට "පරිශීලක එකතු කරන්න" ක්ලික් කරන්න.',
    confirmDeleteUser: 'ඇත්තටම ඔබට මෙම පරිශීලකයා මකා දැමීමට අවශ්‍යද?',
    userDeletedSuccess: 'පරිශීලකයා සාර්ථකව මකන ලදි!',
    userCreateSuccess: 'පරිශීලකයා සාර්ථකව නිර්මාණය කරන ලදි!',
    userUpdateSuccess: 'පරිශීලකයා සාර්ථකව යාවත්කාලීන කරන ලදි!',
      passwordsDoNotMatch: 'මුරපද වල ගැටළුවක් ඇත!',
      pleaseFillRequired: 'අවශ්‍ය ක්ෂේත්‍රය පිරවීමට කරුණාකර!',
      passwordRequired: 'නව පරිශීලකයන් සඳහා මුරපදයක් අවශ්‍යයි!',
      failedToSaveUser: 'පරිශීලකයා සුරැකිම අසාර්ථකයි',
      loading: 'පිරවීම...',
      nameLabel: 'නාමය',
      statusLabel: 'තත්ත්වය',
      actionsLabel: 'ක්‍රියා',
      fullNameLabel: 'සම්පූර්ණ නම',
      designationLabel: 'තනතුර',
      genderLabel: 'ලිංගය',
      nicLabel: 'NIC',
      subSectionLabel: 'උප-අංශ',
      mealManagementTitle: 'ආහාර කළමනාකරණය',
      bookNewMeal: 'උපහාරයක් වෙන්කරන්න',
      mealDateLabel: 'ආහාර දිනය',
      mealTypeLabel: 'ආහාර වර්ගය',
      selectMealType: 'ආහාර වර්ගය තෝරන්න',
      mealTypeBreakfast: '🌅 Breakfast',
      mealTypeLunch: '☀️ Lunch',
      mealTypeDinner: '🌙 Dinner',
      mealTypeSnack: '🍪 Snack',
      expectedQuantityLabel: 'ඔක්කම එල්ලවීම',
      specialRequirementsLabel: 'විශේෂ අවශ්‍යතා',
      specialRequirementsPlaceholder: 'ආහාර රිසිල්, ඇලර්ජි හෝ විශේෂ උපදෙස් මෙහි ලියන්න...',
      bookMeal: 'ආහාරය වෙන්කරන්න',
      bookingInProgress: 'වැඩිදියුණු කිරීම...',
      todaysBookingsLabel: 'අදගේ වෙන්කිරීම්',
      bookingInfoTitle: 'වෙන්කිරීම් තොරතුරු',
      bookingInfo_line1: 'පෙන්වීම් පෙර සැකසිය යුතුය',
      bookingInfo_line2: 'වෙන්කිරීමේ කාලසීමාව: දිනකට පෙර 09:00',
      bookingInfo_line3: 'කැෆේටේරියාවේ සාමාන්‍ය ආහාර ලබාගත හැක',
      bookingInfo_line4: 'විශේෂ ආහාර අවශ්‍යතා සලකා බලන්න',
      bookingInfo_line5: 'වාර්තා වාර්තා ජනනය වෙත ලබා ගත හැක',
      errorFetchingDivisions: 'වකම් ලබා ගැනීමට දෝෂයක්. කරුණාකර නැවත උත්සාහ කරන්න.',
      errorFetchingSections: 'අංශ ලබා ගැනීමට දෝෂයක්. කරුණාකර නැවත උත්සාහ කරන්න.',
      mealBookingCreated: 'ආහාර වෙන්කිරීම සාර්ථකයි!',
      mealBookingCreateError: 'ආහාර වෙන්කිරීමේ දෝෂයක්',
      mealBookingNetworkError: 'ආහාර වෙන්කිරීමේදී ජාල දෝෂයක් සිදු විය',
      successLabel: 'සාර්ථකයි!',
      errorLabel: 'දෝෂයක්!',
    totalEmployees: 'මුළු සේවකයින්',
    allSubsections: 'උප-අංශ සියලු',
    presentToday: 'අද පවතින',
    activeAttendance: 'සක්‍රීය අටෙන්ඩන්ස්',
    attendanceRateLabel: 'පැමිණීමේ අනුපාතය',
    activeDivisions: 'සක්‍රීය වකවානු',
    allDivisions: 'සියලු වකවානු',
    totalSections: 'මා්ෂික අංශ',
    totalSubSections: 'සබ්-අංශ',
    todaysAttendance: 'අදගේ පැමිණිල්ල',
    presentLabel: 'පවතින',
    absentLabel: 'නැත්නම්',
    monthlyAttendance: 'මාසික පැමිණිල්ල',
    export: 'අපනයනය',
    quickInsights: 'වේගවත් අවබෝධ',
    highAttendance: 'ඉහළ පැමිණීම',
    lateArrivals: 'පසු පැමිණීම්',
    earlyDepartures: 'පූර්ව විශ්‍රාම',
    recentActivity: 'මෑත ක්‍රියාකාරකම්',
    noRecentActivities: 'මෑත ක්‍රියා මොනවදැයි සොයා නොගන්නා ලදි.',
    showAll: 'සියල්ල පෙන්නන්න',
    close: 'ඉරින්න',
  },
  ta: {
    systemSettings: 'கணினி அமைப்புகள்',
    quickActions: 'விரைவான நடவடிக்கைகள்',
    addUser: 'பயனரை சேர்க்கவும்',
    reportGeneration: 'அறிக்கை உருவாக்கம்',
    mealManagement: 'உணவு நிர்வாகம்',
    divisionManagement: 'வகுப்பு நிர்வாகம்',
    sectionManagement: 'வகுதி நிர்வாகம்',
    rolesPermissions: 'பாத்திரங்கள் மற்றும் அனுமதிகள்',
    employeeManagement: 'பணியாளர் நிர்வாகம்',
    attendanceSystem: 'ATTENDANCE SYSTEM',
    poweredBy: '@Powered By IS Division',
    slpaTitle: 'SLPA TIME ATTENDANCE SYSTEM',
    createdBy: 'Created By: IS Division',
    closeSidebar: 'பார்வையை மூடு',
    toggleSidebar: 'பார்வையை மாறுதல்',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    dashboard: 'Dashboard',
    systemTitle: 'Time Attendance System',
    welcome: 'வரவேற்பு',
    welcomeAdmin: 'வரவேற்பு நிர்வாகி',
    greetingMorning: 'காலை வணக்கம்',
    greetingAfternoon: 'மதிய வணக்கம்',
    greetingEvening: 'மாலை வணக்கம்',
    refresh: 'புதுப்பி',
    logout: 'வெளியேறு',
    admin: 'நிர்வாகி',
    saveChanges: 'மாற்றங்களை சேமி',
    general: 'பொதுவான',
    appearance: 'முகவை',
    security: 'பாதுகாப்பு',
    notifications: 'அறிவிப்புகள்',
    dataExport: 'தரவு ஏற்றுமதி',
    language: 'மொழி',
    theme: 'தீம்',
    workingHours: 'பணிநேரம்',
    startTime: 'தொடக்க நேரம்',
    endTime: 'முடிவு நேரம்',
    enableNotificationSound: 'அறிவிப்பு ஒலி இயக்கு',
    notificationEmails: 'அறிவிப்பு மின்னஞ்சல்கள்',
    addMail: 'மின்னஞ்சலைச் சேர்க்கவும்',
    noEmails: 'இனிமேல் எந்த மின்னஞ்சலையும் இணைக்கவில்லை.',
    systemName: 'கணினி பெயர்',
    timezone: 'நேர மண்டலம்',
      userManagement: 'பயனர் நிர்வாகம்',
      noPermissionViewUsers: 'பயனர்களைப் பார்க்க உங்கள் அனுமதி இல்லை. அணுகலுக்கு ஒரு சூப்பர் அட்மின் தொடர்பு கொள்ளவும்.',
      editUser: 'பயனர் திருத்தம்',
      addNewUser: 'புதிய பயனரைச் சேர்க்கவும்',
      firstName: 'முதல் பெயர்',
      lastName: 'கடைசி பெயர்',
      emailLabel: 'மின்னஞ்சல்',
      employeeIdLabel: 'பணியாளர் ID',
      divisionLabel: 'வகுப்பு',
      selectDivision: 'வகுப்பை தேர்வு செய்க',
      roleLabel: 'பாத்திரம்',
      sectionLabel: 'பிரிவு',
      selectSection: 'பிரிவை தேர்ந்தெடுக்கவும்',
      passwordLabel: 'கடவுச்சொல்',
      confirmPasswordLabel: 'கடவுச்சொல்லை உறுதிசெய்க',
      cancel: 'ரத்து செய்',
      updateUser: 'பயனரை புதுப்பிக்கவும்',
      noPermissionAddUser: 'பயனர்களைச் சேர்க்க அங்கீகாரம் இல்லை',
      noUsersFound: 'பயனர்கள் எதுவும் இல்லை. முதல் பயனரை உருவாக்க "பயனரைச் சேர்க்க" கிளிக் செய்க.',
      confirmDeleteUser: 'இந்த பயனரை நீக்க வேண்டுமா?',
      userDeletedSuccess: 'பயனர் வெற்றிகரமாக நீக்கப்பட்டது!',
      userCreateSuccess: 'பயனர் வெற்றிகரமாக உருவாக்கப்பட்டது!',
      userUpdateSuccess: 'பயனர் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    fullNameLabel: 'முழு பெயர்',
    designationLabel: 'பதவி',
    genderLabel: 'பாலினம்',
    nicLabel: 'NIC',
    subSectionLabel: 'உப பிரிவு',
    mealManagementTitle: 'உணவு நிர்வாகம்',
    bookNewMeal: 'புது உணவை பதிவு செய்க',
    mealDateLabel: 'உணவு தேதி',
    mealTypeLabel: 'உணவு வகை',
    selectMealType: 'உணவு வகையை தேர்ந்தெடுக்கவும்',
    mealTypeBreakfast: '🌅 Breakfast',
    mealTypeLunch: '☀️ Lunch',
    mealTypeDinner: '🌙 Dinner',
    mealTypeSnack: '🍪 Snack',
    expectedQuantityLabel: 'எதிர்பார்ப்பு எண்ணிக்கை',
    specialRequirementsLabel: 'சிறப்பு தேவைகள்',
    specialRequirementsPlaceholder: 'உணவுப் பற்றிய குறைகள், அசாதாரணங்கள் அல்லது குறிப்புகள் இங்கு...',
    bookMeal: 'உணவை பதிவு செய்க',
    bookingInProgress: 'பதிவேற்படுத்தப்படுகிறது...',
    todaysBookingsLabel: "இன்றைய பதிவு",
    bookingInfoTitle: 'பதிவு தகவல்கள்',
    bookingInfo_line1: 'பதிவுகள் முன்னதாகவே செய்ய வேண்டும்',
    bookingInfo_line2: 'பதிவு கடைசித் தேதி: தினமும் காலை 09:00',
    bookingInfo_line3: 'பாதுகாப்பு உணவுகள் கேஃபெட்டீரியாவில் கிடைக்கின்றன',
    bookingInfo_line4: 'சிறப்பு உணவுப் பொறுப்புகள் குறிப்பிடப்பட்டுள்ளன',
    bookingInfo_line5: 'வகைகள் Report Generation இல் கிடைக்கும்',
    errorFetchingDivisions: 'வகைகள் எடுக்கப்பட வருவதில் பிழை. தயவு செய்து மீண்டும் முயற்சிக்கவும்.',
    errorFetchingSections: 'பிரிவுகளை பெறுவதில் பிழை. தயவு செய்து மீண்டும் முயற்சிக்கவும்.',
    mealBookingCreated: 'உணவு பதிவு வெற்றிகரமாக உருவாக்கப்பட்டது!',
    mealBookingCreateError: 'உணவு பதிவு செய்யும் போது பிழை ஏற்பட்டது',
    mealBookingNetworkError: 'உணவு பதிவு செய்யாத போது நெட்வொர்க் பிழை ஏற்பட்டது',
    successLabel: 'வெற்றி!',
    errorLabel: 'பிழை!',
    totalEmployees: 'மொத்த ஊழியர்கள்',
    allSubsections: 'எல்லா உபப் பிரிவுகள்',
    presentToday: 'இன்று குறிப்பிடப்பட்டவர்கள்',
    activeAttendance: 'செயலில்_attendance',
    attendanceRateLabel: 'உறுப்பினர் வீதம்',
    activeDivisions: 'செயலில் பிரிவுகள்',
    allDivisions: 'அனைத்து பிரிவுகள்',
    totalSections: 'மொத்த பிரிவுகள்',
    totalSubSections: 'மொத்த உப பிரிவுகள்',
    todaysAttendance: "இToday's Attendance",
    presentLabel: 'இங்கு',
    absentLabel: 'கிடையாது',
    monthlyAttendance: 'மாதாந்திர வருகை',
    export: 'எக்ஸ்போர்ட்',
    quickInsights: 'விரைவு தெளிவு',
    highAttendance: 'உயர் வருகை',
    lateArrivals: 'தாமதமாக வந்தவர்கள்',
    earlyDepartures: 'முன்கால விடுப்பு',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    noRecentActivities: 'சமீபத்திய செயல்பாடுகள் எதுவுமில்லை.',
    showAll: 'அனைத்தையும் காட்டு',
    close: ' Close',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    try {
      const saved = localStorage.getItem('appLang');
      return saved || 'en';
    } catch (e) {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('appLang', lang);
    } catch (e) {
      // ignore
    }
  }, [lang]);

  const t = (key) => {
    const dict = translations[lang] || translations.en;
    return dict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
